{
 "title": "Linera General",
 "tags": [ "linera" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Proxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Proxy Error rate (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(\n    sum(rate(linera_proxy_request_error{method_name!=\"non_grpc\"}[1m])) by (method_name)\n) / (\n    sum(rate(linera_proxy_request_success{method_name!=\"non_grpc\"}[1m])) by (method_name)\n    +\n    sum(rate(linera_proxy_request_error{method_name!=\"non_grpc\"}[1m])) by (method_name)\n) * 100",
     "legendFormat": "{{method_name}}"
    }
   ]
  },
  {
   "title": "Proxy p99 latency ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(linera_proxy_request_latency_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy p90 latency ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(linera_proxy_request_latency_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy p50 latency ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(linera_proxy_request_latency_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Server Error rate (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "(\n    sum(rate(linera_server_request_error[1m])) by (method_name)\n) / (\n    sum(rate(linera_server_request_success[1m])) by (method_name)\n    +\n    sum(rate(linera_server_request_error[1m])) by (method_name)\n) * 100",
     "legendFormat": "{{method_name}}"
    }
   ]
  },
  {
   "title": "Server p99 latency ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(linera_server_request_latency_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server p90 latency ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(linera_server_request_latency_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server p50 latency ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(linera_server_request_latency_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Linera Execution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Block Execution Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "rate(linera_block_execution_latency_bucket[$__rate_interval])",
     "legendFormat": "{{pod}} - {{le}}"
    }
   ]
  },
  {
   "title": "Open Chains per Shard",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (shard) (linera_open_chain_count)",
     "legendFormat": "shard {{shard}}"
    }
   ]
  },
  {
   "title": "Panics",
   "type": "table",
   "description": "Shard and proxy panics",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "{service=~\"shard-.*\"} |= `panic`"
    },
    {
     "expr": "{service=\"proxy\"} |= `panic`"
    }
   ]
  }
 ]
}