services:
  # Remote Scylla is used instead.
  scylla:
    profiles:
      - local-scylla

  scylla-setup:
    profiles:
      - local-scylla

  shard-init:
    depends_on: !reset {}
    extra_hosts:
      - "scylla=${SCYLLA_HOST:-10.77.77.1}"

  proxy:
    depends_on: !override
      shard-init:
        condition: service_completed_successfully
        required: true

    extra_hosts:
      - "scylla=${SCYLLA_HOST:-10.77.77.1}"

  shard-0:
    extra_hosts:
      - "scylla=${SCYLLA_HOST:-10.77.77.1}"

  shard-1:
    extra_hosts:
      - "scylla=${SCYLLA_HOST:-10.77.77.1}"

  shard-2:
    extra_hosts:
      - "scylla=${SCYLLA_HOST:-10.77.77.1}"

  shard-3:
    extra_hosts:
      - "scylla=${SCYLLA_HOST:-10.77.77.1}"

