{{- if and .Values.gateway.enabled .Values.gateway.envoyClientTrafficPolicy.enabled -}}
{{- $ctp := .Values.gateway.envoyClientTrafficPolicy -}}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: {{ include "linera-validator.fullname" . }}
  labels:
    {{- include "linera-validator.labels" . | nindent 4 }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ include "linera-validator.fullname" . }}
  {{- with $ctp.http2 }}
  http2:
    {{- with .maxConcurrentStreams }}
    maxConcurrentStreams: {{ int . }}
    {{- end }}
    {{- with .initialStreamWindowSize }}
    initialStreamWindowSize: {{ int . }}
    {{- end }}
    {{- with .initialConnectionWindowSize }}
    initialConnectionWindowSize: {{ int . }}
    {{- end }}
  {{- end }}
  {{- with $ctp.timeout }}
  timeout:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
