{{- if not .Values.validator.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "linera-validator.configSecretName" . }}
  labels:
    {{- include "linera-validator.labels" . | nindent 4 }}
type: Opaque
stringData:
  serverConfig: {{ default "{}" .Values.validator.serverConfigData | toString | quote }}
  genesisConfig: {{ default "{}" .Values.validator.genesisConfigData | toString | quote }}
{{- end -}}
